Controllers/CourseController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using StickaTillsammans.Data;
using StickaTillsammans.Models;

namespace StickaTillsammans.Controllers
{
    public class CourseController : Controller
    {
        private readonly ApplicationDbContext _context;
        private readonly IWebHostEnvironment _hostEnvironment;
        private readonly string wwwRootPath;

        public CourseController(ApplicationDbContext context, IWebHostEnvironment hostEnvironment)
        {
            _context = context;
            _hostEnvironment = hostEnvironment;
            wwwRootPath = hostEnvironment.WebRootPath;
        }
        [Authorize]
        // GET: Course
        public async Task<IActionResult> Index()
        {
            return View(await _context.Courses.ToListAsync());
        }
        public async Task<IActionResult> CoursePublic()
        {
            var dataCourse = _context.Courses.Include(_ => _.Participants).ToListAsync();
            return View(await dataCourse);
        }
        [Authorize]
        // GET: Course/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var course = await _context.Courses
                .Include(_ => _.Participants).Where(m => m.Id == id).FirstOrDefaultAsync(m => m.Id == id);
            if (course == null)
            {
                return NotFound();
            }

            return View(course);
        }

        // GET: Course/Details/5
        public async Task<IActionResult> DetailsPublic(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var course = await _context.Courses
                .Include(_ => _.Participants).Where(m => m.Id == id).FirstOrDefaultAsync(m => m.Id == id);
            if (course == null)
            {
                return NotFound();
            }

            return View(course);
        }
        [Authorize]
        // GET: Course/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Course/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize]
        public async Task<IActionResult> Create([Bind("Id,Title,Date,Time,Price,Spots,Description,ImageFile")] Course course)
        {
            if (ModelState.IsValid)
            {
                if (course.ImageFile != null)
                {
                    //Skapa unikt namn
                    string fileName = Path.GetFileNameWithoutExtension(course.ImageFile.FileName);
                    string extension = Path.GetExtension(course.ImageFile.FileName);

                    course.ImageName = fileName = fileName.Replace(" ", String.Empty) + DateTime.Now.ToString("yymmssfff") + extension;

                    string path = Path.Combine(wwwRootPath + "/images", fileName);

                    // Spara i filsystemet
                    using (var fileStream = new FileStream(path, FileMode.Create))
                    {
                        await course.ImageFile.CopyToAsync(fileStream);
                    }
                }
                else
                {
                    course.ImageName = "placeholder.jpg";
                }

                _context.Add(course);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(course);
        }

        // GET: Course/Edit/5
        [Authorize]
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var course = await _context.Courses.FindAsync(id);
            if (course == null)
            {
                return NotFound();
            }
            return View(course);
        }
        [Authorize]
        // POST: Course/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,Title,Date,Time,Price,Spots,Description,ImageName,ImageFile")] Course course)
        {
            if (id != course.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    if (course.ImageFile != null)
                    {
                        course.ImageName = " ";

                        //Skapa unikt namn
                        string fileName = Path.GetFileNameWithoutExtension(course.ImageFile.FileName);
                        string extension = Path.GetExtension(course.ImageFile.FileName);

                        course.ImageName = fileName = fileName.Replace(" ", String.Empty) + DateTime.Now.ToString("yymmssfff") + extension;

                        string path = Path.Combine(wwwRootPath + "/images", fileName);

                        // Spara i filsystemet
                        using (var fileStream = new FileStream(path, FileMode.Create))
                        {
                            await course.ImageFile.CopyToAsync(fileStream);
                        }
                    }
                    else if (course.ImageName == null && course.ImageFile == null)
                    {
                        course.ImageName = "placeholder.jpg";
                    }
                    else
                    {
                        course.ImageName = course.ImageName;
                    }

                    _context.Update(course);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!CourseExists(course.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(course);
        }
        [Authorize]
        // GET: Course/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var course = await _context.Courses
                .FirstOrDefaultAsync(m => m.Id == id);
            if (course == null)
            {
                return NotFound();
            }

            return View(course);
        }
        [Authorize]
        // POST: Course/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var course = await _context.Courses.FindAsync(id);
            if (course != null)
            {
                _context.Courses.Remove(course);
            }

            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool CourseExists(int id)
        {
            return _context.Courses.Any(e => e.Id == id);
        }
    }
}

Controllers/ParticipantController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using NuGet.Protocol;
using StickaTillsammans.Data;
using StickaTillsammans.Models;

namespace StickaTillsammans.Controllers
{
    public class ParticipantController : Controller
    {
        private readonly ApplicationDbContext _context;

        public ParticipantController(ApplicationDbContext context)
        {
            _context = context;
        }
        [Authorize]
        // GET: Participant
        public async Task<IActionResult> Index()
        {
            var applicationDbContext = _context.Participants.Include(p => p.Course);
            return View(await applicationDbContext.ToListAsync());
        }
        [Authorize]
        // GET: Participant/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var participant = await _context.Participants
                .Include(p => p.Course)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (participant == null)
            {
                return NotFound();
            }

            return View(participant);
        }

        // GET: Participant/Create
        public IActionResult Create()
        {
            ViewData["CourseId"] = new SelectList(_context.Courses, "Id", "Title");
            return View();
        }

        // POST: Participant/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,Name,Email,Tel,Spots,CourseId")] Participant participant)
        {

            if (ModelState.IsValid)
            {
                _context.Add(participant);
                await _context.SaveChangesAsync();
                return RedirectToAction("DetailsPublic", "Course", new { id = participant.CourseId });
            }
            ViewData["CourseId"] = new SelectList(_context.Courses, "Id", "Title", participant.CourseId);
            return View(participant);
        }
        [Authorize]
        // GET: Participant/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var participant = await _context.Participants.FindAsync(id);
            if (participant == null)
            {
                return NotFound();
            }
            ViewData["CourseId"] = new SelectList(_context.Courses, "Id", "Title", participant.CourseId);
            return View(participant);
        }

        // POST: Participant/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize]
        public async Task<IActionResult> Edit(int id, [Bind("Id,Name,Email,Tel,Spots,CourseId")] Participant participant)
        {
            if (id != participant.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(participant);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!ParticipantExists(participant.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction("Details", "Course", new { id = participant.CourseId });
            }
            ViewData["CourseId"] = new SelectList(_context.Courses, "Id", "Title", participant.CourseId);
            return View(participant);
        }
        [Authorize]
        // GET: Participant/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var participant = await _context.Participants
                .Include(p => p.Course)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (participant == null)
            {
                return NotFound();
            }

            return View(participant);
        }

        // POST: Participant/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        [Authorize]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var participant = await _context.Participants.FindAsync(id);
            if (participant != null)
            {
                _context.Participants.Remove(participant);
            }

            await _context.SaveChangesAsync();
            return RedirectToAction("Details", "Course", new { id = participant.CourseId });
        }

        private bool ParticipantExists(int id)
        {
            return _context.Participants.Any(e => e.Id == id);
        }
    }
}

Views/Course/CoursePublic.cshtml
@model IEnumerable<StickaTillsammans.Models.Course>

@{
    ViewData["Title"] = "Boka kurs";
}
<div class="container">
<h2>Våra workshop</h2>

    <div class="row-container row row-cols-1 row-cols-sm-2 row-cols-md-3">
        @foreach (var item in Model)
        {
            <div class="col">
                <div class="card">
                    <a asp-controller="Course" asp-action="DetailsPublic" asp-route-id="@item.Id"><img src="~/images/@item.ImageName" class="card-img-top" alt="@item.ImageName"></a>
                    <div class="card-body">
                        <h5 class="card-title">@item.Title</h5>
                        <a asp-controller="Course" asp-action="DetailsPublic" asp-route-id="@item.Id">Boka workshop <i class="fa-solid fa-arrow-right"></i></a>
                        @{
                            var i = 0;
                        foreach(var p in item.Participants)
                        {
                            i = i + Convert.ToInt32(@p.Spots);
                        }
                        
                        var r = @item.Spots - i;

                        if (r <= 0){
                        <div class="remaining-spots filled">
                            Fullsatt
                            </div>
                        } else {
                        <div class="remaining-spots">
                            @r kvar
                            </div>
                        }
                        }
                    </div>
                </div>
            </div>
        }
    </div>
</div>

Views/Course/Create.cshtml
@model StickaTillsammans.Models.Course

@{
    ViewData["Title"] = "Skapa ny kurs";
}

<div class="container">
<h2>@ViewData["Title"]</h2>
<div class="row align-items-center justify-content-center">
    <div class="col-md-4">
        <form asp-action="Create" enctype="multipart/form-data">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Title" class="control-label"></label>
                <input asp-for="Title" class="form-control" />
                <span asp-validation-for="Title" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Date" class="control-label"></label>
                <input asp-for="Date" class="form-control" />
                <span asp-validation-for="Date" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Time" class="control-label"></label>
                <input asp-for="Time" class="form-control" />
                <span asp-validation-for="Time" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Price" class="control-label"></label>
                <input asp-for="Price" class="form-control" />
                <span asp-validation-for="Price" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Spots" class="control-label"></label>
                <input asp-for="Spots" class="form-control" />
                <span asp-validation-for="Spots" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Description" class="control-label"></label><br/>
                        @Html.EditorFor(model => model.Description, new
                        {
                            htmlAttributes = new
                            {
                                rows = "4",
                                @class =
                                "form-control"
                            }
                        })
                <span asp-validation-for="Description" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="ImageFile" class="control-label"></label>
                <input asp-for="ImageFile" class="form-control" />
                <span asp-validation-for="ImageFile" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Skapa kurs" class="btn btn-success" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index"><i class="fa-solid fa-arrow-left"></i> Tillbaka till listan</a>
</div>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Views/Course/Delete.cshtml
@model StickaTillsammans.Models.Course

@{
    ViewData["Title"] = "Ta bort kurs";
}
<div class="container">
    <h2>@ViewData["Title"]</h2>
    <div class="row align-items-center justify-content-center">
        <hr />
        <h3>Är du säker på att du vill ta bort denna kurs?</h3>
        <dl class="row">
            <dt class="col-sm-2">
                @Html.DisplayNameFor(model => model.Title)
            </dt>
            <dd class="col-sm-10">
                @Html.DisplayFor(model => model.Title)
            </dd>
            <dt class="col-sm-2">
                @Html.DisplayNameFor(model => model.Date)
            </dt>
            <dd class="col-sm-10">
                @Html.DisplayFor(model => model.Date)
            </dd>
            <dt class="col-sm-2">
                @Html.DisplayNameFor(model => model.Time)
            </dt>
            <dd class="col-sm-10">
                @Html.DisplayFor(model => model.Time)
            </dd>
            <dt class="col-sm-2">
                @Html.DisplayNameFor(model => model.Description)
            </dt>
            <dd class="col-sm-10">
                @Html.DisplayFor(model => model.Description)
            </dd>
        </dl>

        <form asp-action="Delete">
            <input type="hidden" asp-for="Id" />
            <input type="submit" value="Ta bort" class="btn btn-danger" />
        </form>
        <div>
            <a asp-action="Index"><i class="fa-solid fa-arrow-left"></i> Tillbaka till listan</a>
        </div>
    </div>
</div>

Views/Course/Details.cshtml
@model StickaTillsammans.Models.Course

@{
    ViewData["Title"] = "Kursdetaljer";
}
<div class="container">
    <h2>@ViewData["Title"]</h2>

    <div>
        <hr />
        <dl class="row">
            <div class="row col-sm-6">
                <dt class="col-sm-2">
                    @Html.DisplayNameFor(model => model.Title):
                </dt>
                <dd class="col-sm-10">
                    @Html.DisplayFor(model => model.Title)
                </dd>
                <dt class="col-sm-2">
                    @Html.DisplayNameFor(model => model.Date):
                </dt>
                <dd class="col-sm-10">
                    @Html.DisplayFor(model => model.Date)
                </dd>
                <dt class="col-sm-2">
                    @Html.DisplayNameFor(model => model.Time):
                </dt>
                <dd class="col-sm-10">
                    @Html.DisplayFor(model => model.Time)
                </dd>
                <dt class="col-sm-2">
                    @Html.DisplayNameFor(model => model.Price):
                </dt>
                <dd class="col-sm-10">
                    @Html.DisplayFor(model => model.Price)
                </dd>
                <dt class="col-sm-2">
                    @Html.DisplayNameFor(model => model.Spots):
                </dt>
                <dd class="col-sm-10">
                    @Html.DisplayFor(model => model.Spots)
                </dd>
                <dt class="col-sm-2">
                    @Html.DisplayNameFor(model => model.Description):
                </dt>
                <dd class="col-sm-10">
                    @Html.DisplayFor(model => model.Description)
                </dd>
            </div>
            <div class="row col-sm-6">
                <dt class="col-sm-2">
                    @Html.DisplayNameFor(model => model.ImageName):
                </dt>
                <dd class="col-sm-10">
                    <img class="img-fluid" src="/images/@Html.DisplayFor(model => model.ImageName)" alt="@Model.ImageName">
                </dd>
            </div>
            <a class="btn btn-primary" asp-action="Edit" asp-route-id="@Model?.Id"><i class="fa-solid fa-pen"></i>
                Redigera detaljer</a>
            <hr />
            <h3>
                @Html.DisplayNameFor(model => model.Participants)
            </h3>
            <table class="table">
                <thead>
                    <th>Namn</th>
                    <th>Epost</th>
                    <th>Telefon</th>
                    <th>Kursplatser</th>
                    <th></th>
                </thead>
                <tbody>
                    @foreach (var p in Model.Participants)
                    {
                        <tr>
                            <td>@p.Name</td>
                            <td>@p.Email</td>
                            <td>@p.Tel</td>
                            <td>@p.Spots</td>
                            <td>
                                <a asp-controller="Participant" asp-action="Edit" asp-route-id="@p.Id"><i class="fa-solid fa-pen"></i> Redigera</a> |
                                <a asp-controller="Participant" asp-action="Delete" asp-route-id="@p.Id"><i class="fa-solid fa-trash"></i> Ta bort</a>
                            </td>
                        </tr>
                    }
                </tbody>
            </table>
        </dl>
    </div>
    <div>
        <a asp-action="Index"><i class="fa-solid fa-arrow-left"></i> Tillbaka till listan</a> |
    </div>
</div>

Views/Course/DetailsPublic.cshtml
@model StickaTillsammans.Models.Course

@{
    ViewData["Title"] = @Html.DisplayFor(model => model.Title);
}
<div class="container">

    <div class="workshop">
        <dl class="row">
            <div class="col-sm-8">
                <dd class="col-sm-10">
                    <img class="img-fluid" src="/images/@Html.DisplayFor(model => model.ImageName)" alt="@Model.ImageName">
                </dd>
            </div>
            <div class="col-sm-4">
                <h2>@Html.DisplayFor(model => model.Title)</h2>
                <p>
                    @Html.DisplayFor(model => model.Date) <br/>
                    kl.@Html.DisplayFor(model => model.Time)
                </p>
                <div class="row price">
                    @Html.DisplayFor(model => model.Price) SEK
                    @{
                        var i = 0;
                        foreach (var p in Model.Participants)
                        {
                            i = i + Convert.ToInt32(@p.Spots);
                        }

                        var r = Model.Spots - i;

                        if (r <= 0)
                        {
                            <div class="remaining-spots filled">
                                Fullsatt
                            </div>
                        }
                        else
                        {
                            <div class="remaining-spots">
                                @r kvar
                            </div>
                            <a asp-controller="Participant" asp-action="Create">Boka plats <i
                                    class="fa-solid fa-arrow-right"></i></a>
                        }
                    }
                </div>
                @if (@Model.Description != null)
                {
                    <h3>@Html.DisplayNameFor(model => model.Description)</h3>
                    <p>@Html.DisplayFor(model => model.Description)</p>
                }
            </div>
        </dl>
    </div>
</div>

Views/Course/Edit.cshtml
@model StickaTillsammans.Models.Course

@{
    ViewData["Title"] = "Redigera kurs";
}
<div class="container">
    <h2>@ViewData["Title"]: @Html.DisplayFor(model => model.Title)</h2>
    <div class="row align-items-center justify-content-center">
        <div class="col-md-4">
            <form asp-action="Edit" enctype="multipart/form-data">
                <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                <input type="hidden" asp-for="Id" />
                <div class="form-group">
                    <label asp-for="Title" class="control-label"></label>
                    <input asp-for="Title" class="form-control" />
                    <span asp-validation-for="Title" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="Date" class="control-label"></label>
                    <input asp-for="Date" class="form-control" />
                    <span asp-validation-for="Date" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="Time" class="control-label"></label>
                    <input asp-for="Time" class="form-control" />
                    <span asp-validation-for="Time" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="Price" class="control-label"></label>
                    <input asp-for="Price" class="form-control" />
                    <span asp-validation-for="Price" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="Spots" class="control-label"></label>
                    <input asp-for="Spots" class="form-control" />
                    <span asp-validation-for="Spots" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="Description" class="control-label"></label><br/>
                    @Html.EditorFor(model => model.Description, new
                        {
                            htmlAttributes = new
                            {
                                rows = "4",
                                @class =
                                "form-control"
                            }
                        })
                    <span asp-validation-for="Description" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="ImageName" class="control-label"></label>
                    <input asp-for="ImageName" class="form-control" />
                    <span asp-validation-for="ImageName" class="text-danger"></span>
                </div>
                <p>Ladda upp en ny bild: </p>
                <div class="form-group">
                    <label asp-for="ImageFile" class="control-label"></label>
                    <input asp-for="ImageFile" class="form-control" />
                    <span asp-validation-for="ImageFile" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <input type="submit" value="Spara" class="btn btn-success" />
                </div>
            </form>
        </div>
    </div>

    <div>
        <a asp-action="Index"><i class="fa-solid fa-arrow-left"></i> Tillbaka till listan</a>
    </div>
</div>

@section Scripts {
    @{
        await Html.RenderPartialAsync("_ValidationScriptsPartial");
    }
}

Views/Course/Index.cshtml
@model IEnumerable<StickaTillsammans.Models.Course>

@{
    ViewData["Title"] = "Kurser Admin";
}
<div class="container">
    <h2>@ViewData["Title"]</h2>
    <p>
        Här syns alla inlagda kurser. Det går att se alla detaljer för en kurs genom att klicka på kurstiteln.
        Alla kurser går att redigera eller ta bort.<br/>
        Under tabellen går det att skapa en ny kurs. 
    </p>
    <table class="table">
        <thead>
            <tr>
                <th>
                    @Html.DisplayNameFor(model => model.Title)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.Date)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.Time)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.Price)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.Spots)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.ImageName)
                </th>
                <th></th>
            </tr>
        </thead>
        <tbody>
            @foreach (var item in Model)
            {
                <tr>
                    <td>
                    <a asp-action="Details" asp-route-id="@item.Id">
                        @Html.DisplayFor(modelItem => item.Title)
                    </a>
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Date)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Time)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Price)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Spots)
                    </td>
                    <td>
                        <img height="50px" src="images/@Html.DisplayFor(modelItem => item.ImageName)" alt="@item.ImageName">
                    </td>
                    <td>
                        <a asp-action="Edit" asp-route-id="@item.Id"><i class="fa-solid fa-pen"></i> Redigera</a> |
                        <a asp-action="Delete" asp-route-id="@item.Id"><i class="fa-solid fa-trash"></i> Ta bort</a>
                    </td>
                </tr>
            }
        </tbody>
    </table>
    <a class="btn btn-primary" asp-action="Create">Skapa ny kurs <i class="fa-solid fa-plus"></i></a>
</div>